  var COUNTRY_CODES = {
    BD: '880',
    BE: '32',
    BF: '226',
    BG: '359',
    BA: '387',
    BB: '+1-246',
    WF: '681',
    BL: '590',
    BM: '+1-441',
    BN: '673',
    BO: '591',
    BH: '973',
    BI: '257',
    BJ: '229',
    BT: '975',
    JM: '+1-876',
    BV: '',
    BW: '267',
    WS: '685',
    BQ: '599',
    BR: '55',
    BS: '+1-242',
    JE: '+44-1534',
    BY: '375',
    BZ: '501',
    RU: '7',
    RW: '250',
    RS: '381',
    TL: '670',
    RE: '262',
    TM: '993',
    TJ: '992',
    RO: '40',
    TK: '690',
    GW: '245',
    GU: '+1-671',
    GT: '502',
    GS: '',
    GR: '30',
    GQ: '240',
    GP: '590',
    JP: '81',
    GY: '592',
    GG: '+44-1481',
    GF: '594',
    GE: '995',
    GD: '+1-473',
    GB: '44',
    GA: '241',
    SV: '503',
    GN: '224',
    GM: '220',
    GL: '299',
    GI: '350',
    GH: '233',
    OM: '968',
    TN: '216',
    JO: '962',
    HR: '385',
    HT: '509',
    HU: '36',
    HK: '852',
    HN: '504',
    HM: ' ',
    VE: '58',
    PR: ['+1-787', '1-939'],
    PS: '970',
    PW: '680',
    PT: '351',
    SJ: '47',
    PY: '595',
    IQ: '964',
    PA: '507',
    PF: '689',
    PG: '675',
    PE: '51',
    PK: '92',
    PH: '63',
    PN: '870',
    PL: '48',
    PM: '508',
    ZM: '260',
    EH: '212',
    EE: '372',
    EG: '20',
    ZA: '27',
    EC: '593',
    IT: '39',
    VN: '84',
    SB: '677',
    ET: '251',
    SO: '252',
    ZW: '263',
    SA: '966',
    ES: '34',
    ER: '291',
    ME: '382',
    MD: '373',
    MG: '261',
    MF: '590',
    MA: '212',
    MC: '377',
    UZ: '998',
    MM: '95',
    ML: '223',
    MO: '853',
    MN: '976',
    MH: '692',
    MK: '389',
    MU: '230',
    MT: '356',
    MW: '265',
    MV: '960',
    MQ: '596',
    MP: '+1-670',
    MS: '+1-664',
    MR: '222',
    IM: '+44-1624',
    UG: '256',
    TZ: '255',
    MY: '60',
    MX: '52',
    IL: '972',
    FR: '33',
    IO: '246',
    SH: '290',
    FI: '358',
    FJ: '679',
    FK: '500',
    FM: '691',
    FO: '298',
    NI: '505',
    NL: '31',
    NO: '47',
    NA: '264',
    VU: '678',
    NC: '687',
    NE: '227',
    NF: '672',
    NG: '234',
    NZ: '64',
    NP: '977',
    NR: '674',
    NU: '683',
    CK: '682',
    XK: '',
    CI: '225',
    CH: '41',
    CO: '57',
    CN: '86',
    CM: '237',
    CL: '56',
    CC: '61',
    CA: '1',
    CG: '242',
    CF: '236',
    CD: '243',
    CZ: '420',
    CY: '357',
    CX: '61',
    CR: '506',
    CW: '599',
    CV: '238',
    CU: '53',
    SZ: '268',
    SY: '963',
    SX: '599',
    KG: '996',
    KE: '254',
    SS: '211',
    SR: '597',
    KI: '686',
    KH: '855',
    KN: '+1-869',
    KM: '269',
    ST: '239',
    SK: '421',
    KR: '82',
    SI: '386',
    KP: '850',
    KW: '965',
    SN: '221',
    SM: '378',
    SL: '232',
    SC: '248',
    KZ: '7',
    KY: '+1-345',
    SG: '65',
    SE: '46',
    SD: '249',
    DO: ['+1-809', '1-829'],
    DM: '+1-767',
    DJ: '253',
    DK: '45',
    VG: '+1-284',
    DE: '49',
    YE: '967',
    DZ: '213',
    US: '1',
    UY: '598',
    YT: '262',
    UM: '1',
    LB: '961',
    LC: '+1-758',
    LA: '856',
    TV: '688',
    TW: '886',
    TT: '+1-868',
    TR: '90',
    LK: '94',
    LI: '423',
    LV: '371',
    TO: '676',
    LT: '370',
    LU: '352',
    LR: '231',
    LS: '266',
    TH: '66',
    TF: '',
    TG: '228',
    TD: '235',
    TC: '+1-649',
    LY: '218',
    VA: '379',
    VC: '+1-784',
    AE: '971',
    AD: '376',
    AG: '+1-268',
    AF: '93',
    AI: '+1-264',
    VI: '+1-340',
    IS: '354',
    IR: '98',
    AM: '374',
    AL: '355',
    AO: '244',
    AQ: '',
    AS: '+1-684',
    AR: '54',
    AU: '61',
    AT: '43',
    AW: '297',
    IN: '91',
    AX: '+358-18',
    AZ: '994',
    IE: '353',
    ID: '62',
    UA: '380',
    QA: '974',
    MZ: '258',
  }
  var HTTP_STATUS = {
    OK: 200,
    PERMANENT_REDIRECT: 301,
    REDIRECT: 302,
    BAD_REQUEST: 400,
    BAD_REQUEST_CUSTOM_MSG: 420,
    SERVER_ERROR: 500,
    NOT_FOUND: 404,
    FORBIDDEN: 403,
    UNAUTHORIZED: 401,
    DEVICE_TOKEN_EXISTS: 492,
    TOKEN_EXPIRED: 498,
    INVALID_PARAMETER: 600,
    NOT_A_GROUP_MEMBER: 601,
    NOT_A_GROUP_ADMIN: 602,
    PROFILE_NOT_TEACHER: 603,
    PROFILE_EXISTS: 604,
    ONLY_ONE_PROFILE: 605,
    PROFILE_HAS_ACTIVE_GROUPS: 606,
    MEDIA_IN_PROCESSING: 607,
    GROUP_TYPE_ALREADY_EXISTS: 608,
    ALREADY_GROUP_MEMBER: 609,
    BANNED_GROUP_MEMBER: 610,
    INVALID_SECRET: 611,
    ALREADY_ACKNOWLEDGED: 612,
    TOO_MANY_REQUESTS: 429,
    SERVER_BAD_REQUEST: 700,
    FREE_PLUGIN_PACKAGE: 729,
    USER_NOT_SUBSCRIBED: 350,
    PAYMENT_TRXN_SKIP: 397,
    COUPON_CODE_EXPIRED: 398,
    USER_ALREADY_SUBSCRIBED: 399,
    USER_SUBSCRIPTION_REQUIRED: 250,
    USER_SUBSCRIPTION_EXPIRED: 299,
    SERVER_ERROR_CODE: 449,
    PLUGIN_ALREADY_ACTIVE: 221,
    PLUGIN_ALREADY_DEACTIVE: 222,
    NO_PLUGINS_ACTIVE_IN_GROUP: 331,
    PRMOTIONAL_ERROR_CODE: 332,
  }
  var VALID_URL_REGEX =
    /^(http(?:s)?\:\/\/[a-zA-Z0-9]+(?:(?:\.|\-)[a-zA-Z0-9]+)+(?:\:\d+)?(?:\/[\w\-]+)*(?:\/?|\/\w+\.[a-zA-Z]{2,4}(?:\?[\w]+\=[\w\-]+)?)?(?:\&[\w]+\=[\w\-]+)*)$/
  var VALID_MEDIA_TYPE = {
    IMAGE: ['jpg', 'jpeg', 'png'],
    AUDIO: ['3gp'],
  }
  const TIMEZONES = [
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Addis_Ababa',
    'Africa/Algiers',
    'Africa/Asmara',
    'Africa/Asmera',
    'Africa/Bamako',
    'Africa/Bangui',
    'Africa/Banjul',
    'Africa/Bissau',
    'Africa/Blantyre',
    'Africa/Brazzaville',
    'Africa/Bujumbura',
    'Africa/Cairo',
    'Africa/Casablanca',
    'Africa/Ceuta',
    'Africa/Conakry',
    'Africa/Dakar',
    'Africa/Dar_es_Salaam',
    'Africa/Djibouti',
    'Africa/Douala',
    'Africa/El_Aaiun',
    'Africa/Freetown',
    'Africa/Gaborone',
    'Africa/Harare',
    'Africa/Johannesburg',
    'Africa/Juba',
    'Africa/Kampala',
    'Africa/Khartoum',
    'Africa/Kigali',
    'Africa/Kinshasa',
    'Africa/Lagos',
    'Africa/Libreville',
    'Africa/Lome',
    'Africa/Luanda',
    'Africa/Lubumbashi',
    'Africa/Lusaka',
    'Africa/Malabo',
    'Africa/Maputo',
    'Africa/Maseru',
    'Africa/Mbabane',
    'Africa/Mogadishu',
    'Africa/Monrovia',
    'Africa/Nairobi',
    'Africa/Ndjamena',
    'Africa/Niamey',
    'Africa/Nouakchott',
    'Africa/Ouagadougou',
    'Africa/Porto-Novo',
    'Africa/Sao_Tome',
    'Africa/Timbuktu',
    'Africa/Tripoli',
    'Africa/Tunis',
    'Africa/Windhoek',
    'America/Adak',
    'America/Anchorage',
    'America/Anguilla',
    'America/Antigua',
    'America/Araguaina',
    'America/Argentina/Buenos_Aires',
    'America/Argentina/Catamarca',
    'America/Argentina/ComodRivadavia',
    'America/Argentina/Cordoba',
    'America/Argentina/Jujuy',
    'America/Argentina/La_Rioja',
    'America/Argentina/Mendoza',
    'America/Argentina/Rio_Gallegos',
    'America/Argentina/Salta',
    'America/Argentina/San_Juan',
    'America/Argentina/San_Luis',
    'America/Argentina/Tucuman',
    'America/Argentina/Ushuaia',
    'America/Aruba',
    'America/Asuncion',
    'America/Atikokan',
    'America/Atka',
    'America/Bahia',
    'America/Bahia_Banderas',
    'America/Barbados',
    'America/Belem',
    'America/Belize',
    'America/Blanc-Sablon',
    'America/Boa_Vista',
    'America/Bogota',
    'America/Boise',
    'America/Buenos_Aires',
    'America/Cambridge_Bay',
    'America/Campo_Grande',
    'America/Cancun',
    'America/Caracas',
    'America/Catamarca',
    'America/Cayenne',
    'America/Cayman',
    'America/Chicago',
    'America/Chihuahua',
    'America/Coral_Harbour',
    'America/Cordoba',
    'America/Costa_Rica',
    'America/Creston',
    'America/Cuiaba',
    'America/Curacao',
    'America/Danmarkshavn',
    'America/Dawson',
    'America/Dawson_Creek',
    'America/Denver',
    'America/Detroit',
    'America/Dominica',
    'America/Edmonton',
    'America/Eirunepe',
    'America/El_Salvador',
    'America/Ensenada',
    'America/Fort_Nelson',
    'America/Fort_Wayne',
    'America/Fortaleza',
    'America/Glace_Bay',
    'America/Godthab',
    'America/Goose_Bay',
    'America/Grand_Turk',
    'America/Grenada',
    'America/Guadeloupe',
    'America/Guatemala',
    'America/Guayaquil',
    'America/Guyana',
    'America/Halifax',
    'America/Havana',
    'America/Hermosillo',
    'America/Indiana/Indianapolis',
    'America/Indiana/Knox',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Tell_City',
    'America/Indiana/Vevay',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Indianapolis',
    'America/Inuvik',
    'America/Iqaluit',
    'America/Jamaica',
    'America/Jujuy',
    'America/Juneau',
    'America/Kentucky/Louisville',
    'America/Kentucky/Monticello',
    'America/Knox_IN',
    'America/Kralendijk',
    'America/La_Paz',
    'America/Lima',
    'America/Los_Angeles',
    'America/Louisville',
    'America/Lower_Princes',
    'America/Maceio',
    'America/Managua',
    'America/Manaus',
    'America/Marigot',
    'America/Martinique',
    'America/Matamoros',
    'America/Mazatlan',
    'America/Mendoza',
    'America/Menominee',
    'America/Merida',
    'America/Metlakatla',
    'America/Mexico_City',
    'America/Miquelon',
    'America/Moncton',
    'America/Monterrey',
    'America/Montevideo',
    'America/Montreal',
    'America/Montserrat',
    'America/Nassau',
    'America/New_York',
    'America/Nipigon',
    'America/Nome',
    'America/Noronha',
    'America/North_Dakota/Beulah',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/Ojinaga',
    'America/Panama',
    'America/Pangnirtung',
    'America/Paramaribo',
    'America/Phoenix',
    'America/Port-au-Prince',
    'America/Port_of_Spain',
    'America/Porto_Acre',
    'America/Porto_Velho',
    'America/Puerto_Rico',
    'America/Punta_Arenas',
    'America/Rainy_River',
    'America/Rankin_Inlet',
    'America/Recife',
    'America/Regina',
    'America/Resolute',
    'America/Rio_Branco',
    'America/Rosario',
    'America/Santa_Isabel',
    'America/Santarem',
    'America/Santiago',
    'America/Santo_Domingo',
    'America/Sao_Paulo',
    'America/Scoresbysund',
    'America/Shiprock',
    'America/Sitka',
    'America/St_Barthelemy',
    'America/St_Johns',
    'America/St_Kitts',
    'America/St_Lucia',
    'America/St_Thomas',
    'America/St_Vincent',
    'America/Swift_Current',
    'America/Tegucigalpa',
    'America/Thule',
    'America/Thunder_Bay',
    'America/Tijuana',
    'America/Toronto',
    'America/Tortola',
    'America/Vancouver',
    'America/Virgin',
    'America/Whitehorse',
    'America/Winnipeg',
    'America/Yakutat',
    'America/Yellowknife',
    'Antarctica/Casey',
    'Antarctica/Davis',
    'Antarctica/DumontDUrville',
    'Antarctica/Macquarie',
    'Antarctica/Mawson',
    'Antarctica/McMurdo',
    'Antarctica/Palmer',
    'Antarctica/Rothera',
    'Antarctica/South_Pole',
    'Antarctica/Syowa',
    'Antarctica/Troll',
    'Antarctica/Vostok',
    'Arctic/Longyearbyen',
    'Asia/Aden',
    'Asia/Almaty',
    'Asia/Amman',
    'Asia/Anadyr',
    'Asia/Aqtau',
    'Asia/Aqtobe',
    'Asia/Ashgabat',
    'Asia/Ashkhabad',
    'Asia/Atyrau',
    'Asia/Baghdad',
    'Asia/Bahrain',
    'Asia/Baku',
    'Asia/Bangkok',
    'Asia/Barnaul',
    'Asia/Beirut',
    'Asia/Bishkek',
    'Asia/Brunei',
    'Asia/Calcutta',
    'Asia/Chita',
    'Asia/Choibalsan',
    'Asia/Chongqing',
    'Asia/Chungking',
    'Asia/Colombo',
    'Asia/Dacca',
    'Asia/Damascus',
    'Asia/Dhaka',
    'Asia/Dili',
    'Asia/Dubai',
    'Asia/Dushanbe',
    'Asia/Famagusta',
    'Asia/Gaza',
    'Asia/Harbin',
    'Asia/Hebron',
    'Asia/Ho_Chi_Minh',
    'Asia/Hong_Kong',
    'Asia/Hovd',
    'Asia/Irkutsk',
    'Asia/Istanbul',
    'Asia/Jakarta',
    'Asia/Jayapura',
    'Asia/Jerusalem',
    'Asia/Kabul',
    'Asia/Kamchatka',
    'Asia/Karachi',
    'Asia/Kashgar',
    'Asia/Kathmandu',
    'Asia/Katmandu',
    'Asia/Khandyga',
    'Asia/Kolkata',
    'Asia/Krasnoyarsk',
    'Asia/Kuala_Lumpur',
    'Asia/Kuching',
    'Asia/Kuwait',
    'Asia/Macao',
    'Asia/Macau',
    'Asia/Magadan',
    'Asia/Makassar',
    'Asia/Manila',
    'Asia/Muscat',
    'Asia/Nicosia',
    'Asia/Novokuznetsk',
    'Asia/Novosibirsk',
    'Asia/Omsk',
    'Asia/Oral',
    'Asia/Phnom_Penh',
    'Asia/Pontianak',
    'Asia/Pyongyang',
    'Asia/Qatar',
    'Asia/Qyzylorda',
    'Asia/Rangoon',
    'Asia/Riyadh',
    'Asia/Saigon',
    'Asia/Sakhalin',
    'Asia/Samarkand',
    'Asia/Seoul',
    'Asia/Shanghai',
    'Asia/Singapore',
    'Asia/Srednekolymsk',
    'Asia/Taipei',
    'Asia/Tashkent',
    'Asia/Tbilisi',
    'Asia/Tehran',
    'Asia/Tel_Aviv',
    'Asia/Thimbu',
    'Asia/Thimphu',
    'Asia/Tokyo',
    'Asia/Tomsk',
    'Asia/Ujung_Pandang',
    'Asia/Ulaanbaatar',
    'Asia/Ulan_Bator',
    'Asia/Urumqi',
    'Asia/Ust-Nera',
    'Asia/Vientiane',
    'Asia/Vladivostok',
    'Asia/Yakutsk',
    'Asia/Yangon',
    'Asia/Yekaterinburg',
    'Asia/Yerevan',
    'Atlantic/Azores',
    'Atlantic/Bermuda',
    'Atlantic/Canary',
    'Atlantic/Cape_Verde',
    'Atlantic/Faeroe',
    'Atlantic/Faroe',
    'Atlantic/Jan_Mayen',
    'Atlantic/Madeira',
    'Atlantic/Reykjavik',
    'Atlantic/South_Georgia',
    'Atlantic/St_Helena',
    'Atlantic/Stanley',
    'Australia/ACT',
    'Australia/Adelaide',
    'Australia/Brisbane',
    'Australia/Broken_Hill',
    'Australia/Canberra',
    'Australia/Currie',
    'Australia/Darwin',
    'Australia/Eucla',
    'Australia/Hobart',
    'Australia/LHI',
    'Australia/Lindeman',
    'Australia/Lord_Howe',
    'Australia/Melbourne',
    'Australia/NSW',
    'Australia/North',
    'Australia/Perth',
    'Australia/Queensland',
    'Australia/South',
    'Australia/Sydney',
    'Australia/Tasmania',
    'Australia/Victoria',
    'Australia/West',
    'Australia/Yancowinna',
    'Brazil/Acre',
    'Brazil/DeNoronha',
    'Brazil/East',
    'Brazil/West',
    'CET',
    'CST6CDT',
    'Canada/Atlantic',
    'Canada/Central',
    'Canada/Eastern',
    'Canada/Mountain',
    'Canada/Newfoundland',
    'Canada/Pacific',
    'Canada/Saskatchewan',
    'Canada/Yukon',
    'Chile/Continental',
    'Chile/EasterIsland',
    'Cuba',
    'EET',
    'EST',
    'EST5EDT',
    'Egypt',
    'Eire',
    'Etc/GMT',
    'Etc/GMT+0',
    'Etc/GMT+1',
    'Etc/GMT+10',
    'Etc/GMT+11',
    'Etc/GMT+12',
    'Etc/GMT+2',
    'Etc/GMT+3',
    'Etc/GMT+4',
    'Etc/GMT+5',
    'Etc/GMT+6',
    'Etc/GMT+7',
    'Etc/GMT+8',
    'Etc/GMT+9',
    'Etc/GMT-0',
    'Etc/GMT-1',
    'Etc/GMT-10',
    'Etc/GMT-11',
    'Etc/GMT-12',
    'Etc/GMT-13',
    'Etc/GMT-14',
    'Etc/GMT-2',
    'Etc/GMT-3',
    'Etc/GMT-4',
    'Etc/GMT-5',
    'Etc/GMT-6',
    'Etc/GMT-7',
    'Etc/GMT-8',
    'Etc/GMT-9',
    'Etc/GMT0',
    'Etc/Greenwich',
    'Etc/UCT',
    'Etc/UTC',
    'Etc/Universal',
    'Etc/Zulu',
    'Europe/Amsterdam',
    'Europe/Andorra',
    'Europe/Astrakhan',
    'Europe/Athens',
    'Europe/Belfast',
    'Europe/Belgrade',
    'Europe/Berlin',
    'Europe/Bratislava',
    'Europe/Brussels',
    'Europe/Bucharest',
    'Europe/Budapest',
    'Europe/Busingen',
    'Europe/Chisinau',
    'Europe/Copenhagen',
    'Europe/Dublin',
    'Europe/Gibraltar',
    'Europe/Guernsey',
    'Europe/Helsinki',
    'Europe/Isle_of_Man',
    'Europe/Istanbul',
    'Europe/Jersey',
    'Europe/Kaliningrad',
    'Europe/Kiev',
    'Europe/Kirov',
    'Europe/Lisbon',
    'Europe/Ljubljana',
    'Europe/London',
    'Europe/Luxembourg',
    'Europe/Madrid',
    'Europe/Malta',
    'Europe/Mariehamn',
    'Europe/Minsk',
    'Europe/Monaco',
    'Europe/Moscow',
    'Europe/Nicosia',
    'Europe/Oslo',
    'Europe/Paris',
    'Europe/Podgorica',
    'Europe/Prague',
    'Europe/Riga',
    'Europe/Rome',
    'Europe/Samara',
    'Europe/San_Marino',
    'Europe/Sarajevo',
    'Europe/Saratov',
    'Europe/Simferopol',
    'Europe/Skopje',
    'Europe/Sofia',
    'Europe/Stockholm',
    'Europe/Tallinn',
    'Europe/Tirane',
    'Europe/Tiraspol',
    'Europe/Ulyanovsk',
    'Europe/Uzhgorod',
    'Europe/Vaduz',
    'Europe/Vatican',
    'Europe/Vienna',
    'Europe/Vilnius',
    'Europe/Volgograd',
    'Europe/Warsaw',
    'Europe/Zagreb',
    'Europe/Zaporozhye',
    'Europe/Zurich',
    'GB',
    'GB-Eire',
    'GMT',
    'GMT+0',
    'GMT-0',
    'GMT0',
    'Greenwich',
    'HST',
    'Hongkong',
    'Iceland',
    'Indian/Antananarivo',
    'Indian/Chagos',
    'Indian/Christmas',
    'Indian/Cocos',
    'Indian/Comoro',
    'Indian/Kerguelen',
    'Indian/Mahe',
    'Indian/Maldives',
    'Indian/Mauritius',
    'Indian/Mayotte',
    'Indian/Reunion',
    'Iran',
    'Israel',
    'Jamaica',
    'Japan',
    'Kwajalein',
    'Libya',
    'MET',
    'MST',
    'MST7MDT',
    'Mexico/BajaNorte',
    'Mexico/BajaSur',
    'Mexico/General',
    'NZ',
    'NZ-CHAT',
    'Navajo',
    'PRC',
    'PST8PDT',
    'Pacific/Apia',
    'Pacific/Auckland',
    'Pacific/Bougainville',
    'Pacific/Chatham',
    'Pacific/Chuuk',
    'Pacific/Easter',
    'Pacific/Efate',
    'Pacific/Enderbury',
    'Pacific/Fakaofo',
    'Pacific/Fiji',
    'Pacific/Funafuti',
    'Pacific/Galapagos',
    'Pacific/Gambier',
    'Pacific/Guadalcanal',
    'Pacific/Guam',
    'Pacific/Honolulu',
    'Pacific/Johnston',
    'Pacific/Kiritimati',
    'Pacific/Kosrae',
    'Pacific/Kwajalein',
    'Pacific/Majuro',
    'Pacific/Marquesas',
    'Pacific/Midway',
    'Pacific/Nauru',
    'Pacific/Niue',
    'Pacific/Norfolk',
    'Pacific/Noumea',
    'Pacific/Pago_Pago',
    'Pacific/Palau',
    'Pacific/Pitcairn',
    'Pacific/Pohnpei',
    'Pacific/Ponape',
    'Pacific/Port_Moresby',
    'Pacific/Rarotonga',
    'Pacific/Saipan',
    'Pacific/Samoa',
    'Pacific/Tahiti',
    'Pacific/Tarawa',
    'Pacific/Tongatapu',
    'Pacific/Truk',
    'Pacific/Wake',
    'Pacific/Wallis',
    'Pacific/Yap',
    'Poland',
    'Portugal',
    'ROC',
    'ROK',
    'Singapore',
    'Turkey',
    'UCT',
    'US/Alaska',
    'US/Aleutian',
    'US/Arizona',
    'US/Central',
    'US/East-Indiana',
    'US/Eastern',
    'US/Hawaii',
    'US/Indiana-Starke',
    'US/Michigan',
    'US/Mountain',
    'US/Pacific',
    'US/Pacific-New',
    'US/Samoa',
    'UTC',
    'Universal',
    'W-SU',
    'WET',
    'Zulu',
  ]
  const MONTHS = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December',
  }
  var COUNTRY_NAME_BASED_ON_CODE = {
    93: 'Afghanistan',
    355: 'Albania',
    213: 'Algeria',
    684: 'American Samoa',
    376: 'Andorra',
    244: 'Angola',
    809: 'Anguilla',
    672: 'Antartica',
    1268: 'Antigua and Barbuda',
    54: 'Argentina',
    374: 'Armenia',
    297: 'Aruba',
    61: 'Australia',
    43: 'Austria',
    994: 'Azerbaijan',
    809: 'Bahamas',
    973: 'Bahrain',
    880: 'Bangladesh',
    809: 'Barbados',
    375: 'Belarus',
    32: 'Belgium',
    501: 'Belize',
    229: 'Benin',
    '1 441': 'Bermuda',
    975: 'Bhutan',
    591: 'Bolivia',
    387: 'Bosnia and Herzegowina',
    267: 'Botswana',
    55: 'Bouvet Island',
    55: 'Brazil',
    246: 'British Indian Ocean Territory',
    673: 'Brunei Darussalam',
    359: 'Bulgaria',
    226: 'Burkina Faso',
    257: 'Burundi',
    855: 'Cambodia',
    237: 'Cameroon',
    1: 'Canada',
    238: 'Cape Verde',
    ' 345': 'Cayman Islands',
    236: 'Central African Republic',
    235: 'Chad',
    56: 'Chile',
    86: 'China',
    61: 'Christmas Island',
    61: 'Cocos Islands',
    57: 'Colombia',
    269: 'Comoros',
    242: 'Congo',
    682: 'Cook Islands',
    506: 'Costa Rica',
    225: "Cota D'Ivoire",
    385: 'Croatia',
    53: 'Cuba',
    357: 'Cyprus',
    420: 'Czech Republic',
    45: 'Denmark',
    253: 'Djibouti',
    '1 767': 'Dominica',
    '1 849': 'Dominican Republic',
    670: 'East Timor',
    593: 'Ecuador',
    20: 'Egypt',
    503: 'El Salvador',
    240: 'Equatorial Guinea',
    291: 'Eritrea',
    372: 'Estonia',
    251: 'Ethiopia',
    500: 'Falkland Islands',
    298: 'Faroe Islands',
    679: 'Fiji',
    358: 'Finland',
    33: 'France',
    33: 'France Metropolitan',
    594: 'French Guiana',
    689: 'French Polynesia',
    262: 'French Southern Territories',
    241: 'Gabon',
    220: 'Gambia',
    995: 'Georgia',
    49: 'Germany',
    233: 'Ghana',
    350: 'Gibraltar',
    30: 'Greece',
    299: 'Greenland',
    '1 473': 'Grenada',
    590: 'Guadeloupe',
    671: 'Guam',
    502: 'Guatemala',
    224: 'Guinea',
    225: 'Guinea-Bissau',
    592: 'Guyana',
    509: 'Haiti',
    39: 'Holy See',
    504: 'Honduras',
    852: 'Hong Kong',
    36: 'Hungary',
    354: 'Iceland',
    91: 'India',
    62: 'Indonesia',
    98: 'Iran',
    964: 'Iraq',
    353: 'Ireland',
    972: 'Israel',
    39: 'Italy',
    '1 876': 'Jamaica',
    81: 'Japan',
    962: 'Jordan',
    7: 'Kazakhstan',
    254: 'Kenya',
    686: 'Kiribati',
    850: "Democratic People's Republic of Korea",
    82: 'Korea',
    965: 'Kuwait',
    996: 'Kyrgyzstan',
    856: 'Lao',
    371: 'Latvia',
    961: 'Lebanon',
    266: 'Lesotho',
    231: 'Liberia',
    218: 'Libya',
    41: 'Liechtenstein',
    370: 'Lithuania',
    352: 'Luxembourg',
    853: 'Macau',
    389: 'Macedonia',
    261: 'Madagascar',
    265: 'Malawi',
    60: 'Malaysia',
    960: 'Maldives',
    223: 'Mali',
    356: 'Malta',
    692: 'Marshall Islands',
    596: 'Martinique',
    222: 'Mauritania',
    230: 'Mauritius',
    262: 'Mayotte',
    52: 'Mexico',
    691: 'Micronesia',
    373: 'Moldova',
    377: 'Monaco',
    976: 'Mongolia',
    1664: 'Montserrat',
    212: 'Morocco',
    258: 'Mozambique',
    95: 'Myanmar',
    264: 'Namibia',
    674: 'Nauru',
    977: 'Nepal',
    31: 'Netherlands',
    599: 'Netherlands Antilles',
    687: 'New Caledonia',
    64: 'New Zealand',
    505: 'Nicaragua',
    227: 'Niger',
    234: 'Nigeria',
    683: 'Niue',
    672: 'Norfolk Island',
    '1 670': 'Northern Mariana Islands',
    47: 'Norway',
    968: 'Oman',
    92: 'Pakistan',
    680: 'Palau',
    507: 'Panama',
    675: 'Papua New Guinea',
    595: 'Paraguay',
    51: 'Peru',
    63: 'Philippines',
    872: 'Pitcairn',
    48: 'Poland',
    351: 'Portugal',
    '1 939': 'Puerto Rico',
    974: 'Qatar',
    262: 'Reunion',
    40: 'Romania',
    7: 'Russia',
    250: 'Rwanda',
    '1 869': 'Saint Kitts and Nevis',
    '1 758': 'Saint LUCIA',
    '1 784': 'Saint Vincent',
    685: 'Samoa',
    378: 'San Marino',
    239: 'Sao Tome and Principe',
    966: 'Saudi Arabia',
    221: 'Senegal',
    248: 'Seychelles',
    232: 'Sierra',
    65: 'Singapore',
    421: 'Slovakia',
    386: 'Slovenia',
    677: 'Solomon Islands',
    252: 'Somalia',
    27: 'South Africa',
    500: 'South Georgia',
    34: 'Spain',
    94: 'SriLanka',
    290: 'St. Helena',
    508: 'St. Pierre and Miguelon',
    249: 'Sudan',
    597: 'Suriname',
    47: 'Svalbard',
    268: 'Swaziland',
    46: 'Sweden',
    41: 'Switzerland',
    963: 'Syria',
    886: 'Taiwan',
    7: 'Tajikistan',
    255: 'Tanzania',
    66: 'Thailand',
    228: 'Togo',
    690: 'Tokelau',
    676: 'Tonga',
    '1 868': 'Trinidad and Tobago',
    216: 'Tunisia',
    90: 'Turkey',
    993: 'Turkmenistan',
    '1 649': 'Turks and Caicos',
    688: 'Tuvalu',
    256: 'Uganda',
    380: 'Ukraine',
    971: 'United Arab Emirates',
    44: 'United Kingdom',
    1: 'United States',
    '1-808': 'United States Minor Outlying Islands',
    598: 'Uruguay',
    7: 'Uzbekistan',
    678: 'Vanuatu',
    58: 'Venezuela',
    84: 'Vietnam',
    '1 284': 'Virgin Islands (British)',
    '1 340': 'Virgin Islands (U.S)',
    681: 'Wallis and Futana Islands',
    212: 'Western Sahara',
    967: 'Yemen',
    38: 'Yugoslavia',
    260: 'Zambia',
    263: 'Zimbabwe',
  }  
  const TIME_IN_MILLIS = {
    TEN_MINS: 600000,
    TWENTY_TWO_MINS: 1320000,
    ONE_HOUR: 3600000,
  }
  const errors = {
    invalid_parameters: 'Invalid Parameters',
    server_error: 'Failed to process the request.',
  }
  const constants = {
    HTTP_STATUS: HTTP_STATUS,
    COUNTRY_CODES: COUNTRY_CODES,
    OTP_LENGTH: 6,
    VALID_URL_REGEX: VALID_URL_REGEX,
    VALID_MEDIA_TYPE: VALID_MEDIA_TYPE,
    TIMEZONES: TIMEZONES,
    MONTHS: MONTHS,
    COUNTRY_NAME_BASED_ON_CODE,
    TIME_IN_MILLIS,
    ERRORS: errors
  }
  
  module.exports = constants
  